break_into_partial_movies: false
camera_resolutions:
  ultra_high: 3840x2160
  default_resolution: ultra_high
  high: 1920x1080
  low: 854x480
  medium: 1280x720
directories:
  mirror_module_path: false
  # Output path of the video
  output: gen/videos
  # Raster image
  raster_images: gen/images
  # Audio file
  sounds: gen/sounds
  # Temporary dir
  temporary_storage: gen/tmp
fps: 60
full_screen: false
style:
  background_color: '#333333'
  font: Consolas
  tex_template: default
universal_import_line: |
  from manimlib import *
  import numpy as np
window_monitor: 0
window_position: UR
